[workspace]
members = [ "main" , "payroll-domain"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Katsutoshi Itoh"]
description = "agile software development"
documentation = "https://www.amazon.co.jp/dp/4797347783"
edition = "2021"

[workspace.dependencies]

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
