[package]
name = "tx-app"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.95"
log.workspace = true

payroll-domain = { path = "../payroll-domain" }
