[package]
name = "text-parser-tx-source"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
parsec-rs.workspace = true

tx-app = { path = "../tx-app" }
